# Generated by Django 4.2.4 on 2023-08-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gendr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtofavorite',
            old_name='property',
            new_name='gendre',
        ),
    ]
