# Generated by Django 4.2.4 on 2023-08-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendr', '0002_rename_property_addtofavorite_gendre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
