# Generated by Django 4.2.4 on 2023-08-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendr', '0004_alter_all_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
