# Generated by Django 4.2.4 on 2023-08-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gendr', '0005_all_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='video',
        ),
    ]
