# Generated by Django 4.2.4 on 2023-09-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gendr', '0008_all_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='tags',
        ),
    ]
