# Generated by Django 4.2.4 on 2023-10-20 11:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('gendr', '0011_language_all_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
