# Generated by Django 4.2.4 on 2023-10-20 11:53

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('gendr', '0012_all_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='all',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='all',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
