# Generated by Django 4.2.4 on 2023-10-21 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gendr', '0013_remove_all_tag_remove_all_tags_delete_tags_all_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AddToFavorite',
        ),
    ]
